# Generated by Django 3.0.5 on 2021-01-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('rank', models.PositiveIntegerField()),
                ('name', models.CharField(default='', max_length=70)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('artist', models.CharField(default='', max_length=70)),
                ('lfm_link', models.CharField(default='', max_length=70)),
                ('image', models.CharField(default='', max_length=100)),
                ('user', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('rank', models.PositiveIntegerField()),
                ('name', models.CharField(default='', max_length=70)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('lfm_link', models.CharField(default='', max_length=70)),
                ('image', models.CharField(default='', max_length=100)),
                ('user', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('rank', models.PositiveIntegerField()),
                ('track_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=70)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('artist', models.CharField(default='', max_length=70)),
                ('lfm_link', models.CharField(default='', max_length=70)),
                ('image', models.CharField(default='', max_length=100)),
                ('user', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TrackSpotData',
            fields=[
                ('lfm_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(default='', max_length=100)),
                ('danceability', models.FloatField(blank=True, default=None)),
                ('energy', models.FloatField(blank=True, default=None)),
                ('key', models.FloatField(blank=True, default=None)),
                ('loudness', models.FloatField(blank=True, default=None)),
                ('mode', models.FloatField(blank=True, default=None)),
                ('speechiness', models.FloatField(blank=True, default=None)),
                ('acousticness', models.FloatField(blank=True, default=None)),
                ('instrumentalness', models.FloatField(blank=True, default=None)),
                ('liveness', models.FloatField(blank=True, default=None)),
                ('valence', models.FloatField(blank=True, default=None)),
                ('tempo', models.FloatField(blank=True, default=None)),
                ('duration_ms', models.FloatField(blank=True, default=None)),
                ('time_signature', models.FloatField(blank=True, default=None)),
                ('spot_id', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
